### ISSUE TITLE
contribute button doesn't work

### ISSUE THREAD

**Issue by Shreyc711** [PerlDancer/Dancer2#1700] opened 2023-10-24 16:02 UTC
this should redirect us to original GitHub page but it is not working.
![issue](https://github.com/PerlDancer/Dancer2/assets/118420015/f39d2f61-3641-4d30-8916-8bf0ed4fefe9)

**Comment by cromedome** [comment] 2023-11-04 19:45
Shrey, thanks for submitting this issue. 

The contribute link goes to this page by design. There are more ways to contribute to an open source project other than code. Docs and promotion are just as important, as well as actual usage of the software. And there are a couple of other ways to get to Github for Dancer2 (such as the fork ribbon in the upper right of the page).

In light of all this, I am going to close this issue. Again, I appreciate you taking the time to open this, and I hope we see other contributions from you down the road!

**Closed by cromedome** 2023-11-04 19:45 UTC
Labels: Documentation, Won't Fix
