### ISSUE TITLE
Invalid body causes a 500

### ISSUE THREAD

**Issue by xsawyerx** [PerlDancer/Dancer2#1507] opened 2019-07-04 07:48 UTC
When making a call with an invalid body, `HTTP::Body` croaks, which triggers a 400.

I think we should instead return a 400 for an invalid request.

Objections?

**Comment by cromedome** [comment] 2019-07-04 13:13
No objection! :+1:

**Comment by ice-lenor** [comment] 2019-07-04 15:08
The issue is also present in Dancer v1
https://github.com/PerlDancer/Dancer/issues/1167

**Comment by xsawyerx** [comment] 2019-07-08 12:24
Reference tests for this: #1508

**Comment by cromedome** [comment] 2020-04-20 02:02
Resolved by #1509.

**Closed by cromedome** 2020-04-20 02:02 UTC
Labels: Bug
