### ISSUE TITLE
Dancer2::Manual:  Not getting expected error page

### ISSUE THREAD

**Issue by jkeenan** [PerlDancer/Dancer2#1201] opened 2016-07-06 13:43 UTC
From Dancer2::Manual (https://metacpan.org/pod/distribution/Dancer2/lib/Dancer2/Manual.pod#Error-Pages):

_When an HTTP error occurs (the action responds with a status code other than 200), Dancer2 first looks in the public directory for a corresponding HTML file matching the error code (eg: 500.html or 404.html)._

_If such a file exists, it's used to report the error, otherwise, a default error page will be rendered on the fly._

As I work my way through a checkout of this manual, I am simply adding endpoints to the skeleton's lib/mywebapp.pm.  Hence, I would expect that if I called a missing endpoint, I would get the error page found in public/404.html.  Here's a key excerpt from that file:
```html
<h1>Error 404</h1>
<div id="content">
<h2>Page Not Found</h2><p>Sorry, this is the void.</p>
</div>
```
However, when I call a nonexistent endpoint such as "http://localhost:5000/langston", I get a *different* error page whose content includes this:
```html
<h1>Error 404 - Not Found</h1>
<div id="content">
/langston
</div>
```
Indeed, this appears to be rendered from Dancer2::Core::Error::default_error_page() (https://metacpan.org/source/XSAWYERX/Dancer2-0.200002/lib/Dancer2/Core/Error.pm#L101).

Any ideas as to why I am not getting the "Sorry, this is the void." page?

**Comment by xsawyerx** [comment] 2016-07-06 13:46
I think the documentation is not very clear here. Here is the code, and I verified that it works:

```perl
# It doesn't make sense to return a static page if show_errors is on
if ( !$self->show_errors && (my $content = $self->static_page) ) {
    return $content;
}
```

If you were to disable `show_errors` in your configuration (config file or with `set` in the app), it will work.

**Comment by xsawyerx** [comment] 2016-07-06 21:02
I don't consider this a bug, as it is intended behavior. Closing. Thank you.

**Closed by xsawyerx** 2016-07-06 21:02 UTC
