### ISSUE TITLE
Plugins allowed to register (the same) hook multiple times

### ISSUE THREAD

**Issue by b10m** [PerlDancer/Dancer2#888] opened 2015-04-17 21:43 UTC
Consider an app split in multiple files, like:

```
lib/Main.pm
lib/Users.pm
lib/Sales.pm
lib/Admin.pm
```

By using `appname` we can tie them all up in one app and by using `prefix` we can nicely isolate pieces of code in different modules.

Now if I want to use e.g. `Dancer2::Plugin::Deferred` in 3 of them, I _must_ `use` them in all the files I want, for otherwise perl craps out at compile time (it doesn't know about, in this case, the `deferred` keyword). While this shouldn't be a real problem, the `$dsl->app->add_hook` is called all the times, resulting in 3 code blocks. This specific plugin deletes data in this hook, so by the last time it hits, there's no data left. The bigger problem obviously is that we don't want the same coderef to run 3 times, where it shouldn't.

I can hack around this, but a much nicer solution would be to keep track of whether a certain hook is already loaded and silently ignores the other calls.

**Comment by ambs** [comment] 2015-04-18 10:44
Kind of related to this issue: I had a main module, `lib/DA.pm`, that used a couple of submodules, `lib/DA/*.pm`. This was a Dancer (1) app, and I was able to use some of the registered keywords in the submodules (for example, a `lib/DA/Database.pm` used `Dancer::Plugin::Database` and, therefore, used the `dancer` keyword).

During the update noticed that is not possible anymore. At the moment I am doing a workaround, but it would be nice if this would not be needed.

**Comment by druthb** [comment] 2015-04-29 03:22
This issue, in the specific case the OP posted, even, makes `prefix` unusable in an application I'm working on. I don't know whether the Right Thing to do is prevent a hook from being added if one with that name already exists (in `Dancer2::Core::Hook`, I suppose) or to just deal with these as they crop up, as in cases like the two listed here.

**Comment by sherwind** [comment] 2015-06-04 09:20
Yeah it would be nice if the documented way of splitting app doesn't cause plugin hook run multiple times . If it's any help, I use `require` to workaround this issue, like so:

```
# in lib/MyApp.pm
package MyApp;
use Dancer2;
use Dancer2::Plugin::Deferred;

require MyApp::Users;
require MyApp::Sessions;

get {...}
1;

# in lib/MyApp/Users.pm
get {...}
1;

# in lib/MyApp/Sessions.pm
get {...}
1;

**Comment by cxw42** [comment] 2020-01-09 00:32
Personally, I think it would be neat if `user Dancer2 appname=>'...'` automatically pulled any plugin-added DSL keywords from the named app into the using module.  That would at least take care of the OP's case, as far as I can tell.

**Comment by cxw42** [comment] 2020-01-11 22:25
Well, I just did a test and can't reproduce.  Was this already fixed?  I hope so!

My repro is at https://github.com/cxw42/D2Issue888 .  Clone and run `plackup bin/app.psgi`.  It defines GET routes for `/` and `/other`.  Each is in its own .pm file, and each file `use`s SamplePlugin.pm.  I am logging calls to the hook, and only see one call (`SamplePlugin "before" hook` lines):

    $ plackup bin/app.psgi

    (request for '/')
    SamplePlugin BEGIN from main
    SamplePlugin BUILD called SamplePlugin=HASH(0x601ecc168)
    HTTP::Server::PSGI: Accepting connections at http://0:5000/
    [D2Issue888:1891] core @2020-01-11 17:20:59> looking for get / in /home/cxw/perl5/lib/perl5/Dancer2/Core/App.pm l. 36
    [D2Issue888:1891] core @2020-01-11 17:20:59> Entering hook core.app.before_request in (eval 212) l. 1
    SamplePlugin "before" hook called from Dancer2::Core::Hook
    sample_keyword called from Dancer2::Plugin
    [D2Issue888:1891] core @2020-01-11 17:20:59> Entering hook core.app.after_request in (eval 212) l. 1
    127.0.0.1 - - <snip>

    (request for '/other')
    [D2Issue888:1891] core @2020-01-11 17:21:04> looking for get /other in /home/cxw/perl5/lib/perl5/Dancer2/Core/App.pm l. 36
    [D2Issue888:1891] core @2020-01-11 17:21:04> Entering hook core.app.before_request in (eval 212) l. 1
    SamplePlugin "before" hook called from Dancer2::Core::Hook
    sample_keyword called from Dancer2::Plugin
    [D2Issue888:1891] core @2020-01-11 17:21:04> Entering hook core.app.after_request in (eval 212) l. 1
    127.0.0.1 - - <snip>

**Comment by SysPete** [comment] 2020-01-12 12:27
Thank you @cxw42! Yes, this appears to have been fixed by @yanick when adding `with_plugin` via 2639e12bec9225ede7fb836ed07fc5efe377d0ae. That commit ensures that when a single app loads a plugin for a second time, that the already loaded copy of the plugin is used, so no extra routes or hooks get added. Of course if the plugin is loaded into multiple apps, then each app will get its own routes and hooks (etc.) added.

I propose that this issue is closed.

**Comment by cxw42** [comment] 2020-01-12 14:38
@SysPete thanks for confirming!  I will upload a zip of my test repo just for the historical record, then delete the repo.  I looked at @yanick's commit and agree with closing this issue.

**Closed** 2020-01-12 20:41 UTC
Labels: Bug, Question, Sensitive
