### ISSUE TITLE
32 seconds to reload a page?

### ISSUE THREAD

**Issue by sdondley** [PerlDancer/Dancer2#1404] opened 2017-12-04 22:40 UTC
I am completely new to Dancer. Just kicking tires here. I got a fresh Debian install with nginx running and installed Dancer2 from a Debian package. 

I got the sample `MyWeb-App` up and running on port 5000. So far so good. But it seems awful flaky so far. For example, from the home page of the sample app, I clicked on one of the links to the right to a tutorial. Then I hit the back button to go back to my Dancer app running on a local virtual machine. Then I hit refresh and it took 32 seconds for the page to reload. I can duplicate this just about every time. Subsequent refreshes are instantaneous.

What would cause the server to take so long to respond to the request upon the initial refresh request?

**Comment by paveljurca** [comment] 2017-12-04 23:04
This might be caused by a browser as you hit the back button. This is creating an inconsistent state in web applications.

**Comment by sdondley** [comment] 2017-12-04 23:44
I dunno. Never seen anything like this before. It's got to be something with Dancer2.

**Comment by xsawyerx** [comment] 2017-12-05 09:06
This is very surprising. We have been using Dancer2 for a while and I can assure you we would have noticed if it took 32 seconds to run. You're describing a particular situation with a VM as well, which might convey networking issues.

Is it possible for you to narrow it down outside the VM to a reproducible simple case? Otherwise, there really is little we can do to inspect it other than coming over and working on your computer. :)

**Comment by sdondley** [comment] 2017-12-05 10:36
I'm running the site on plack. Most likely, it's an issue with that.

**Comment by xsawyerx** [comment] 2017-12-05 10:46
If you could provide us with sample code, we could try and help verify. But until we see the code we cannot comment on what the problem is and whether there is a problem.

I'm closing this issue but if you can eventually reproduce it (or give us information so we could reproduce it), we will open the ticket again. Thank you. :)

**Closed by xsawyerx** 2017-12-05 10:46 UTC

**Comment by paveljurca** [comment] 2017-12-05 11:07
Maybe troubling port binding, socket opening? If it's just a demo app (no SQL connection, possible loops etc.) the issue is probably outside of the web framework. You may also set the ` set show_errors => 1;` and `set log => 'core'` opts;

**Comment by sdondley** [comment] 2017-12-05 12:03
It's just the sample "Perl is Dancing" page running on plack. I'm guessing it's plack. Not a big deal.

**Comment by sdondley** [comment] 2017-12-07 19:00
So this problem is really bugging me. Reopening with new information. It looks like this problem is related to Google Chrome. I cannot reproduce this problem in Firefox. (Note: I have disabled all Chrome extensions and the problem still happens). Can someone please see if they can reproduce?

So here is the behavior which is reproducible around 40 to 60% of the time for me.

1) Generate a new web app: `dancer2 gen -a MyWeb::App`
2) Visit http://<ip_address>:5000 /with Chrome
3) Hit refresh in Chrome.
4) In Firefox, visit http://<ip_address>:5000/
5) Note the page will not load much of the time in Firefox
6) Open another tab in chrome and visit another web
7) Note the page now instantly loads

So even though the page (sometimes) instantly loads in Chrome, it is actively blocking other visiting from getting access to the app as if it's tying up a socket or something. And something Chrome does when visiting another tab and loading a website triggers the app to load.

**Comment by sdondley** [comment] 2017-12-07 19:04
Not sure if this might be related or not: https://github.com/plack/Plack/issues/208. It's quite an old issue but it's still open.

**Comment by sdondley** [comment] 2017-12-07 19:06
Above issue references this issue with Chrome https://github.com/plack/Plack/issues/191

The issue is still open as well. The difference for me is that it's happening when not in incognito mode.

**Comment by sdondley** [comment] 2017-12-12 17:51
Just to follow up with this so as not to scare anyone away. The issue is definitely not Dancer2. It is Plack running on HTTP::Server::PSGI. This is not a big deal as it is only a testing platform. See https://github.com/plack/Plack/issues/191#issuecomment-350073351 to see comment from miyagawa, the founder of Plack.
