### ISSUE TITLE
Hooks for plugins not registered

### ISSUE THREAD

**Issue by e11it** [PerlDancer/Dancer2#510] opened 2013-11-24 22:01 UTC
It's possible to register hook only for last included plugin.
I have modified test to demonstrate this issue.

Please take a look: https://github.com/e11it/Dancer2/commit/9ed2da3bd2d8c211e7fa11dad78c5715f32b21ea

Test fails with:
```
t/plugin_syntax.t ............ 1/? Invalid hook name `third_hook' at /Dancer2/Core/DSL.pm line 143.
# Child (hooks in plugins) exited without calling finalize()
#   Failed test 'hooks in plugins'
#   at /System/Library/Perl/5.16/Test/Builder.pm line 252.
# Tests were run but no plan was declared and done_testing() was not seen.
```

**Comment by drmuey** [comment] 2015-04-14 23:28
this look like the cause of https://github.com/bigpresh/Dancer-Plugin-Database/issues/62 and https://github.com/PerlDancer/Dancer2-Plugin-Auth-Tiny/issues/4

**Comment by drmuey** [comment] 2015-04-14 23:41
+1 this is stopping a major project I am doing in its tracks so I will paypal $100 to whoever fixes this (I am not familiar enough w/ Dancer2 to offer a patch at this time) ;)

**Comment by veryrusty** [comment] 2015-04-21 14:37
I've made some progress on this, enough for the test from @e11it to pass. See my comment in #889.

**Comment by veryrusty** [comment] 2015-04-25 02:04
There is a working implementation for review in #892. :dancers:

**Comment by veryrusty** [comment] 2015-04-26 11:11
Resolved by #892.

Thanks to @e11it for reporting the issue and thank you to everyones' research, poking and prodding to get the fix/workaround merged.

There is still "brain pain" for anyone working through the plugin code - though we should now have the time to think about the reimplementation :)

**Closed by veryrusty** 2015-04-26 11:11 UTC
Labels: Bug, Testing

**Comment by drmuey** [comment] 2015-05-07 22:58
Unfortunetely, #510 is not resolved by #892 :( its behaving like it was in my previous post

Dancer2 v.160000 and Dancer2::Plugin::Database v 2.12 still give me: 
   `Hook 'database_connected' does not exist at /Users/dmuey/perl5/perlbrew/perls/perl-5.16.0/lib/site_perl/5.16.0/Dancer2/Plugin/Database.pm line 45.`

commenting out line 45, `$dsl->execute_hook(@_);`, (since I am not using the hooks) allows it to work but that is a limited temporary hack :)

**Comment by drmuey** [comment] 2015-05-07 22:58
will open new issue since I can't re-open this one

**Comment by drmuey** [comment] 2015-05-07 22:59
Done it is, #905
