### ISSUE TITLE
The request and response should be (de)serialize data respectively

### ISSUE THREAD

**Issue by JaHIY** [PerlDancer/Dancer2#979] opened 2015-08-21 04:37 UTC
In most cases, we don't need to (de)serialize data in request.

So I suggest that the `serializer` in `config` should be splited into `serializer_for_request` and `serializer_for_response`.

**Comment by veryrusty** [comment] 2015-08-21 04:50
The request body is only deserialized if the request is a PUT, POST, PATCH or DELETE, and the body has length. I suspect these are not "most cases"; @JaHIY Could you please explain your use-case for this ?

**Comment by JaHIY** [comment] 2015-08-21 04:59
@veryrusty It isn't flexible to set the same serializer for request and response. I just want no serializer for request and a `'json` serializer for response.

**Comment by veryrusty** [comment] 2015-08-21 05:29
Dancer2 is meant to be "simple", so an app has one serializer. To me, this smells of a micro-optimisation for a specific use case; I understand the want, but not the need. Hence I want to know more about the specific use case.

Do you have any figures, such as what's your (expected?) proportion of requests that would currently be deserialized but you don't need them to be?  Have you tried a writing a custom serializer that always returns undef or an empty hash on deserialization ? If so, how does that benchmark against the JSON serializer in the core for your use case?

**Comment by JaHIY** [comment] 2015-08-21 06:42
I mean the format of request and response should be independent. A very simple API needn't a `JSON` serializer for request. The `form` way is enough, such as twitter API、CPAN API.

**Comment by JaHIY** [comment] 2015-08-24 02:53
Now I use `app->set_response( Dancer2::Core::Response->new( %{ app->response }, serializer => Dancer2::Serializer::JSON->new ) );` to set serializer for response.

**Comment by xsawyerx** [comment] 2015-08-28 11:34
Hi, @JaHIY, :)

Let me just verify that I understand what you mean and your reasons. Please correct me if I'm wrong.

You would like to separate the serializer into two: one for the request and one for the response. This will allow you (and others) to handle the following situations:
1. Deserialize the request, but do not serialize the response.
2. Serialize the response, but do not serialize the request.
3. Serialize and deserialize using different serializers.

Assuming my understanding is correct, I think this is a feature we do not want to have, because we do not consider it a feature. I have written more extensively on the Perl Dancer Advent Calendar 2014 here: [Serial Serializer](http://advent.perldancer.org/2014/11) (under *Always or never*)

To make it shorter (and save you having to read the article), this produces several problematic situations, the highlights of them are:
* Specialized code to handle two serializers, and the existence or non-existence of serializers.
* Web applications that handle (on request and response) different content type in the same app.

While the key problem with these issues only occurs when you have "serialize or don't, depending on ref" - an issue that your suggestion does *not* introduce, which is good - I am still unconvinced that the requirement is worth the code complexity. For example, the parameter parsing (which I'm trying to move completely into `Hash::MultiValue`) might be *much* harder to handle.

Does that make sense? What do you think?

**Comment by xsawyerx** [comment] 2015-09-19 23:53
Considering this is intended behavior (at least right now) and the discussion doesn't seem to continue (for now), I'm closing this issue. If you would like to continue this conversation, either reopen the ticket, or contact us (IRC, mailing list, etc.).

Have a great day. :)

**Closed by xsawyerx** 2015-09-19 23:53 UTC
