### ISSUE TITLE
[Dancer2 0.200003] Weird behaviour with Plugin Inclusion

### ISSUE THREAD

**Issue by pierre-vigier** [PerlDancer/Dancer2#1216] opened 2016-07-18 07:56 UTC
Hi,

i got an app that was working on Dancer 0.166001 and is breaking with 0.200003 .
Here is a trimmed down version of the problem. Once including Dancer2::Plugin::Database , i get a `Can't locate object method "dsl" via package "DemoApp"` error message

* bin/app.psgi
```perl
#!/usr/bin/env perl
use strict;
use warnings;
use lib 'lib';
use DemoApp;

return DemoApp->to_app;
```

*lib/DemoApp.pm
```perl
package DemoApp;
use DemoApp::Extension;
use Dancer2;

get '/' => sub { return 'root' };

true;
```

*lib/DemoApp/Extension.pm
```perl
package DemoApp::Extension;
use Dancer2 appname => 'DemoApp';
use Dancer2::Plugin::Database;

get '/extension' => sub { 'extension'; };
```

That code runs on Dancer2 0.166001, but not on 0.200003.

Fix is pretty simple, in my code, if i reverse in `lib/DemoApp.pm` the inclusion of Dancer2 and DemoApp::Extension, it is then working as expected:
```perl
package DemoApp;
use Dancer2;
use DemoApp::Extension;
```
instead of
```perl
package DemoApp;
use DemoApp::Extension;
use Dancer2;
```

It might be worth a hint in documentation for people upgrading from a version below 0.200001 to 0.200001 and above.

The code is working properly in 0.200001 and above if in my case the DemoApp::Extension package do not include plugin Dancer2::Plugin::Database .
I can't tell if it's a bug of Dancer2 or of my code, but it's a breaking change. That's happening with other plugin as well, like Dancer2::Plugin::Email.

**Comment by xsawyerx** [comment] 2016-07-18 08:11
What version of the plugins are you using?

**Comment by pierre-vigier** [comment] 2016-07-18 08:32
Should be the last ones,
Dancer2::Plugin::Database => 2.16
Dancer2::Plugin::Email => 0.003
```
> perl -I local/lib/perl5 -MDancer2::Plugin::Database -E 'say $Dancer2::Plugin::Database::VERSION;'
2.16
>perl -I local/lib/perl5 -MDancer2::Plugin::Email -E 'say $Dancer2::Plugin::Email::VERSION;'
0.0003
```

**Comment by xsawyerx** [comment] 2016-07-18 08:50
Preliminary debugging shows that the problem is due to the order here:

* You load `DemoApp`
* This first loads another class: `DemoApp::Extension`.
* It registers an app called `DemoApp`.
* It then loads a plugin which will try to use the `dsl` keyword in `DemoApp` namespace.

Because `DemoApp` itself hasn't run `use Dancer2` yet, it will not have that DSL keyword (or any other DSL keywords) available yet. They will only get used when you call `use Dancer2` inside that class.

You're basically calling a plugin that tries to use keywords for a class that did not import them yet.

**Comment by xsawyerx** [comment] 2016-07-18 08:53
This might work if we shift the call for keywords on the calling class rather than on the app's name as class, but I'm not sure if we can reach it. `caller` is probably not reliable once you have plugins within plugins. We can use the old trick of trying to find `dsl` in it. I'm not sure that's correct design though. (Do we allow someone to define "dsl" somewhere in the hierarchy without it being a Dancer2 app?)

**Comment by pierre-vigier** [comment] 2016-07-18 08:55
I understood the issue, and i already fixed it in my code.
My only concern being that it worked before, i guess an hint in the documentation could be enough, as it makes perfect sense. That's why i am thinking it should probably not considered as a bug. Maybe, if possible, an hint would be enough

**Comment by xsawyerx** [comment] 2016-07-18 09:31
I'm trying to see whether we can really fix it, as in you wouldn't need to change any order. :)

**Comment by xsawyerx** [comment] 2016-07-18 09:33
The following patch in `Dancer2::Plugin` will sort this out, no matter what your order is:

```perl
-                foreach my $keyword ( keys %{$_[0]->app->name->dsl->dsl_keywords} ) {
+                my $app_dsl_cb;
+                ## no critic qw(ControlStructures::ProhibitCStyleForLoops)
+                for ( my $i = 0; my $caller = caller($i); $i++ ) {
+                    $app_dsl_cb = $caller->can('dsl')
+                        and last;
+                }
+
+                $app_dsl_cb
+                    or croak('Could not find Dancer2 app');
+
+                foreach my $keyword ( keys %{ $app_dsl_cb->()->dsl_keywords} ) {
```

I'll prepare a pull request for this.

**Comment by pierre-vigier** [comment] 2016-07-18 09:48
Nice!

**Comment by xsawyerx** [comment] 2016-07-18 09:53
Thank you for raising this issue. :)

**Comment by xsawyerx** [comment] 2016-07-18 11:32
Pull request created. :)

**Comment by xsawyerx** [comment] 2016-07-21 15:21
Merged and will be released soon. Thanks for reporting the issue.

**Closed by xsawyerx** 2016-07-21 15:21 UTC

**Comment by pierre-vigier** [comment] 2016-07-21 16:02
Thanks for the fix
