### ISSUE TITLE
"cpanm --reinstall Dancer2" fails the tests due to "Can't locate WWW/Form/UrlEncoded.pm in @INC (you may need to install the WWW::Form::UrlEncoded module)"

### ISSUE THREAD

**Issue by shlomif** [PerlDancer/Dancer2#1631] opened 2021-09-07 08:15 UTC
Log is:

```
cpanm (App::cpanminus) 1.7044 on perl 5.032001 built for x86_64-linux-gnu-thread-multi
Work directory is /home/shlomif/.cpanm/work/1631001608.244233
You have make /usr/bin/make
You have LWP 6.53
You have /bin/tar: tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching Dancer2 () on cpanmetadb ...
--> Working on Dancer2
Fetching http://www.cpan.org/authors/id/C/CR/CROMEDOME/Dancer2-0.301004.tar.gz
-> OK
Unpacking Dancer2-0.301004.tar.gz
Entering Dancer2-0.301004
Checking configure dependencies from META.json
Checking if you have File::ShareDir::Install 0.06 ... Yes (0.13)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.44)
Checking if you have CPAN::Meta::Requirements 2.120620 ... Yes (2.140)
Checking if you have Module::Metadata 0 ... Yes (1.000037)
Configuring Dancer2-0.301004
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Dancer2
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have IPC::Open3 0 ... Yes (1.21)
Checking if you have Plack::Middleware::RemoveRedundantBody 0 ... Yes (0.09)
Checking if you have Exporter 5.57 ... Yes (5.74)
Checking if you have HTTP::Tiny 0 ... Yes (0.076)
Checking if you have List::Util 1.29 ... Yes (1.56)
Checking if you have Test::Builder 0 ... Yes (1.302186)
Checking if you have Digest::SHA 0 ... Yes (6.02)
Checking if you have URI::Escape 0 ... Yes (5.08)
Checking if you have HTTP::Headers 0 ... Yes (6.33)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.44)
Checking if you have POSIX 0 ... Yes (1.94)
Checking if you have HTTP::Date 0 ... Yes (6.05)
Checking if you have Encode 0 ... Yes (3.12)
Checking if you have File::Copy 0 ... Yes (2.34)
Checking if you have Pod::Simple::SimpleTree 0 ... Yes (3.40)
Checking if you have parent 0 ... Yes (0.238)
Checking if you have Test::EOL 0 ... Yes (2.02)
Checking if you have File::Temp 0 ... Yes (0.2309)
Checking if you have Plack 1.0040 ... Yes (1.0048)
Checking if you have Test::Fatal 0 ... Yes (0.016)
Checking if you have Sub::Quote 0 ... Yes (2.006006)
Checking if you have Ref::Util 0 ... Yes (0.204)
Checking if you have Types::Standard 0 ... Yes (1.012004)
Checking if you have Attribute::Handlers 0 ... Yes (1.01)
Checking if you have Safe::Isa 0 ... Yes (1.000010)
Checking if you have File::Path 0 ... Yes (2.18)
Checking if you have IO::Handle 0 ... Yes (1.48)
Checking if you have Exporter::Tiny 0 ... Yes (1.002002)
Checking if you have CLI::Osprey 0 ... Yes (0.08)
Checking if you have Capture::Tiny 0.12 ... Yes (0.48)
Checking if you have Carp 0 ... Yes (1.50)
Checking if you have Plack::Middleware::FixMissingBodyInRedirect 0 ... Yes (0.12)
Checking if you have Import::Into 0 ... Yes (1.002005)
Checking if you have Template::Tiny 0 ... Yes (1.14)
Checking if you have JSON::MaybeXS 0 ... Yes (1.004003)
Checking if you have HTTP::Cookies 0 ... Yes (6.10)
Checking if you have Moo::Role 0 ... Yes (2.005004)
Checking if you have Hash::MultiValue 0 ... Yes (0.16)
Checking if you have File::Spec 0 ... Yes (3.78)
Checking if you have HTTP::Headers::Fast 0.21 ... Yes (0.22)
Checking if you have MIME::Base64 3.13 ... Yes (3.15)
Checking if you have Moo 2.000000 ... Yes (2.005004)
Checking if you have Role::Tiny 2.000000 ... Yes (2.002004)
Checking if you have Path::Tiny 0 ... Yes (0.118)
Checking if you have Hash::Merge::Simple 0 ... Yes (0.051)
Checking if you have File::Which 0 ... Yes (1.27)
Checking if you have Clone 0 ... Yes (0.45)
Checking if you have File::Share 0 ... Yes (0.25)
Checking if you have Type::Tiny 1.000006 ... Yes (1.012004)
Checking if you have Module::Runtime 0 ... Yes (0.016)
Checking if you have Config::Any 0 ... Yes (0.32)
Checking if you have File::Basename 0 ... Yes (2.85)
Checking if you have Test::More 0.92 ... Yes (1.302186)
Checking if you have YAML 0.86 ... Yes (1.30)
Checking if you have Template 0 ... Yes (3.009)
Building and testing Dancer2-0.301004
cp share/skel/public/favicon.ico blib/lib/auto/share/dist/Dancer2/skel/public/favicon.ico
cp share/skel/t/002_index_route.t blib/lib/auto/share/dist/Dancer2/skel/t/002_index_route.t
cp share/skel/public/images/perldancer-bg.jpg blib/lib/auto/share/dist/Dancer2/skel/public/images/perldancer-bg.jpg
cp share/skel/public/404.html blib/lib/auto/share/dist/Dancer2/skel/public/404.html
cp share/skel/t/001_base.t blib/lib/auto/share/dist/Dancer2/skel/t/001_base.t
cp share/skel/cpanfile blib/lib/auto/share/dist/Dancer2/skel/cpanfile
cp share/skel/environments/production.yml blib/lib/auto/share/dist/Dancer2/skel/environments/production.yml
cp share/skel/bin/+app.psgi blib/lib/auto/share/dist/Dancer2/skel/bin/+app.psgi
cp share/skel/public/css/error.css blib/lib/auto/share/dist/Dancer2/skel/public/css/error.css
cp share/skel/config.yml blib/lib/auto/share/dist/Dancer2/skel/config.yml
cp share/skel/.dancer blib/lib/auto/share/dist/Dancer2/skel/.dancer
cp share/docker/Dockerfile blib/lib/auto/share/dist/Dancer2/docker/Dockerfile
cp share/skel/views/layouts/main.tt blib/lib/auto/share/dist/Dancer2/skel/views/layouts/main.tt
cp share/skel/public/+dispatch.fcgi blib/lib/auto/share/dist/Dancer2/skel/public/+dispatch.fcgi
cp share/skel/environments/development.yml blib/lib/auto/share/dist/Dancer2/skel/environments/development.yml
cp share/skel/public/css/style.css blib/lib/auto/share/dist/Dancer2/skel/public/css/style.css
cp share/skel/lib/AppFile.pm blib/lib/auto/share/dist/Dancer2/skel/lib/AppFile.pm
cp share/skel/public/+dispatch.cgi blib/lib/auto/share/dist/Dancer2/skel/public/+dispatch.cgi
cp share/skel/public/javascripts/jquery.js blib/lib/auto/share/dist/Dancer2/skel/public/javascripts/jquery.js
cp share/skel/public/images/perldancer.jpg blib/lib/auto/share/dist/Dancer2/skel/public/images/perldancer.jpg
cp share/skel/public/500.html blib/lib/auto/share/dist/Dancer2/skel/public/500.html
cp share/skel/Makefile.PL blib/lib/auto/share/dist/Dancer2/skel/Makefile.PL
cp share/skel/MANIFEST.SKIP blib/lib/auto/share/dist/Dancer2/skel/MANIFEST.SKIP
cp share/.gitignore blib/lib/auto/share/dist/Dancer2/.gitignore
cp share/skel/views/index.tt blib/lib/auto/share/dist/Dancer2/skel/views/index.tt
cp lib/Dancer2/Core/Response.pm blib/lib/Dancer2/Core/Response.pm
cp lib/Dancer2/Core/Role/SessionFactory/File.pm blib/lib/Dancer2/Core/Role/SessionFactory/File.pm
cp lib/Dancer2/Core/Dispatcher.pm blib/lib/Dancer2/Core/Dispatcher.pm
cp lib/Dancer2/FileUtils.pm blib/lib/Dancer2/FileUtils.pm
cp lib/Dancer2/Core/Role/Serializer.pm blib/lib/Dancer2/Core/Role/Serializer.pm
cp lib/Dancer2/Core/Role/Engine.pm blib/lib/Dancer2/Core/Role/Engine.pm
cp lib/Dancer2/Core/DSL.pm blib/lib/Dancer2/Core/DSL.pm
cp lib/Dancer2/Core/Runner.pm blib/lib/Dancer2/Core/Runner.pm
cp lib/Dancer2/Core/App.pm blib/lib/Dancer2/Core/App.pm
cp lib/Dancer2/Config.pod blib/lib/Dancer2/Config.pod
cp lib/Dancer2/Core.pm blib/lib/Dancer2/Core.pm
cp lib/Dancer2/Core/Role/SessionFactory.pm blib/lib/Dancer2/Core/Role/SessionFactory.pm
cp lib/Dancer2.pm blib/lib/Dancer2.pm
cp lib/Dancer2/Core/Role/Template.pm blib/lib/Dancer2/Core/Role/Template.pm
cp lib/Dancer2/Core/Cookie.pm blib/lib/Dancer2/Core/Cookie.pm
cp lib/Dancer2/Core/Role/Logger.pm blib/lib/Dancer2/Core/Role/Logger.pm
cp lib/Dancer2/Core/Role/Handler.pm blib/lib/Dancer2/Core/Role/Handler.pm
cp lib/Dancer2/Cookbook.pod blib/lib/Dancer2/Cookbook.pod
cp lib/Dancer2/Core/Hook.pm blib/lib/Dancer2/Core/Hook.pm
cp lib/Dancer2/Core/Role/ConfigReader.pm blib/lib/Dancer2/Core/Role/ConfigReader.pm
cp lib/Dancer2/Core/Role/Hookable.pm blib/lib/Dancer2/Core/Role/Hookable.pm
cp lib/Dancer2/Core/MIME.pm blib/lib/Dancer2/Core/MIME.pm
cp lib/Dancer2/Core/Error.pm blib/lib/Dancer2/Core/Error.pm
cp lib/Dancer2/CLI/Gen.pm blib/lib/Dancer2/CLI/Gen.pm
cp lib/Dancer2/Core/Request.pm blib/lib/Dancer2/Core/Request.pm
cp lib/Dancer2/CLI/Version.pm blib/lib/Dancer2/CLI/Version.pm
cp lib/Dancer2/Core/Session.pm blib/lib/Dancer2/Core/Session.pm
cp lib/Dancer2/Core/Role/StandardResponses.pm blib/lib/Dancer2/Core/Role/StandardResponses.pm
cp lib/Dancer2/Core/Role/HasLocation.pm blib/lib/Dancer2/Core/Role/HasLocation.pm
cp lib/Dancer2/Core/HTTP.pm blib/lib/Dancer2/Core/HTTP.pm
cp lib/Dancer2/Core/Time.pm blib/lib/Dancer2/Core/Time.pm
cp lib/Dancer2/Core/Response/Delayed.pm blib/lib/Dancer2/Core/Response/Delayed.pm
cp lib/Dancer2/Core/Request/Upload.pm blib/lib/Dancer2/Core/Request/Upload.pm
cp lib/Dancer2/Core/Types.pm blib/lib/Dancer2/Core/Types.pm
cp lib/Dancer2/Core/Role/DSL.pm blib/lib/Dancer2/Core/Role/DSL.pm
cp lib/Dancer2/Core/Route.pm blib/lib/Dancer2/Core/Route.pm
cp lib/Dancer2/Core/Factory.pm blib/lib/Dancer2/Core/Factory.pm
cp lib/Dancer2/CLI.pm blib/lib/Dancer2/CLI.pm
cp lib/Dancer2/Serializer/Dumper.pm blib/lib/Dancer2/Serializer/Dumper.pm
cp lib/Dancer2/Logger/Console.pm blib/lib/Dancer2/Logger/Console.pm
cp lib/Dancer2/Plugins.pod blib/lib/Dancer2/Plugins.pod
cp lib/Dancer2/Manual/Migration.pod blib/lib/Dancer2/Manual/Migration.pod
cp lib/Dancer2/Test.pm blib/lib/Dancer2/Test.pm
cp lib/Dancer2/Logger/File.pm blib/lib/Dancer2/Logger/File.pm
cp lib/Dancer2/Manual/Deployment.pod blib/lib/Dancer2/Manual/Deployment.pod
cp lib/Dancer2/Serializer/YAML.pm blib/lib/Dancer2/Serializer/YAML.pm
cp lib/Dancer2/Handler/File.pm blib/lib/Dancer2/Handler/File.pm
cp lib/Dancer2/Logger/Diag.pm blib/lib/Dancer2/Logger/Diag.pm
cp lib/Dancer2/Logger/Capture.pm blib/lib/Dancer2/Logger/Capture.pm
cp lib/Dancer2/Manual.pod blib/lib/Dancer2/Manual.pod
cp lib/Dancer2/Session/YAML.pm blib/lib/Dancer2/Session/YAML.pm
cp lib/Dancer2/Tutorial.pod blib/lib/Dancer2/Tutorial.pod
cp lib/Dancer2/Plugin.pm blib/lib/Dancer2/Plugin.pm
cp lib/Dancer2/Manual/Testing.pod blib/lib/Dancer2/Manual/Testing.pod
cp lib/Dancer2/Template/Tiny.pm blib/lib/Dancer2/Template/Tiny.pm
cp lib/Dancer2/Manual/Keywords.pod blib/lib/Dancer2/Manual/Keywords.pod
cp lib/Dancer2/Logger/Note.pm blib/lib/Dancer2/Logger/Note.pm
cp lib/Dancer2/Policy.pod blib/lib/Dancer2/Policy.pod
cp lib/Dancer2/Session/Simple.pm blib/lib/Dancer2/Session/Simple.pm
cp lib/Dancer2/Handler/AutoPage.pm blib/lib/Dancer2/Handler/AutoPage.pm
cp lib/Dancer2/Template/TemplateToolkit.pm blib/lib/Dancer2/Template/TemplateToolkit.pm
cp lib/Dancer2/Logger/Capture/Trap.pm blib/lib/Dancer2/Logger/Capture/Trap.pm
cp lib/Dancer2/Template/Simple.pm blib/lib/Dancer2/Template/Simple.pm
cp lib/Dancer2/Serializer/JSON.pm blib/lib/Dancer2/Serializer/JSON.pm
cp lib/Dancer2/Logger/Null.pm blib/lib/Dancer2/Logger/Null.pm
cp lib/Dancer2/Serializer/Mutable.pm blib/lib/Dancer2/Serializer/Mutable.pm
cp lib/Dancer2/Template/Implementation/ForkedTiny.pm blib/lib/Dancer2/Template/Implementation/ForkedTiny.pm
cp script/dancer2 blib/script/dancer2
"/usr/bin/perl" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/dancer2
Manifying 1 pod document
Manifying 32 pod documents
Manifying 33 pod documents
Manifying 2 pod documents
Skip blib/lib/auto/share/dist/Dancer2/skel/environments/production.yml (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/MANIFEST.SKIP (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/bin/+app.psgi (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/404.html (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/environments/development.yml (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/config.yml (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/500.html (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/css/style.css (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/t/002_index_route.t (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/views/layouts/main.tt (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/.dancer (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/+dispatch.fcgi (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/.gitignore (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/images/perldancer-bg.jpg (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/+dispatch.cgi (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/javascripts/jquery.js (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/docker/Dockerfile (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/lib/AppFile.pm (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/images/perldancer.jpg (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/views/index.tt (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/cpanfile (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/favicon.ico (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/t/001_base.t (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/Makefile.PL (unchanged)
Skip blib/lib/auto/share/dist/Dancer2/skel/public/css/error.css (unchanged)
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/classes/Dancer2-Core-Factory/*.t t/classes/Dancer2-Core-Hook/*.t t/classes/Dancer2-Core-Request/*.t t/classes/Dancer2-Core-Response-Delayed/*.t t/classes/Dancer2-Core-Response/*.t t/classes/Dancer2-Core-Role-Engine/*.t t/classes/Dancer2-Core-Role-Handler/*.t t/classes/Dancer2-Core-Role-HasLocation/*.t t/classes/Dancer2-Core-Role-Serializer/*.t t/classes/Dancer2-Core-Role-StandardResponses/*.t t/classes/Dancer2-Core-Route/*.t t/classes/Dancer2-Core-Runner/*.t t/classes/Dancer2-Core/*.t t/classes/Dancer2/*.t t/dsl/*.t t/examples/*.t t/issues/*.t t/issues/gh-1013/*.t t/issues/gh-1046/*.t t/issues/gh-1216/*.t t/issues/gh-1226/*.t t/issues/gh-1230/*.t t/issues/gh-639/fails/*.t t/issues/gh-639/succeeds/*.t t/issues/gh-650/*.t t/issues/gh-975/*.t t/issues/memleak/*.t t/plugin2/*.t t/roles/*.t t/route-pod-coverage/*.t t/scope_problems/*.t t/template_tiny/*.t

#   Failed test 'Dancer2.pm loaded ok'
#   at t/00-compile.t line 101.
#          got: '512'
#     expected: '0'
Can't locate WWW/Form/UrlEncoded.pm in @INC (you may need to install the WWW::Form::UrlEncoded module) (@INC contains: /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/arch /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/arch /home/shlomif/perl5/lib/perl5/5.32.1/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1 /home/shlomif/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1 /home/shlomif/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5 /home/shlomif/apps/perl/modules/share/perl5 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/perl5/5.26.1 /home/shlomif/perl5/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.0 /home/shlomif/perl5/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1 /home/shlomif/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5 /home/shlomif/apps/perl/modules/share/perl5 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/perl5/5.26.1 /home/shlomif/apps/perl/modules/share/perl5 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/perl5/5.26.1 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /home/shlomif/perl5/lib/perl5/5.32.0 /home/shlomif/perl5/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.0 /home/shlomif/perl5/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /usr/local/lib/site_perl .) at /home/shlomif/perl5/lib/perl5/HTTP/Entity/Parser/UrlEncoded.pm line 5.
BEGIN failed--compilation aborted at /home/shlomif/perl5/lib/perl5/HTTP/Entity/Parser/UrlEncoded.pm line 5.
Compilation failed in require at /usr/share/perl/5.32/Module/Load.pm line 77.
Can't locate HTTP/Entity/Parser/UrlEncoded in @INC (@INC contains: /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/arch /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/arch /home/shlomif/perl5/lib/perl5/5.32.1/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1 /home/shlomif/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1 /home/shlomif/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5 /home/shlomif/apps/perl/modules/share/perl5 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/perl5/5.26.1 /home/shlomif/perl5/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.0 /home/shlomif/perl5/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.1 /home/shlomif/perl5/lib/perl5/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5 /home/shlomif/apps/perl/modules/share/perl5 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/perl5/5.26.1 /home/shlomif/apps/perl/modules/share/perl5 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/site_perl/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/5.28.0 /home/shlomif/apps/perl/modules/lib/perl5/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/site_perl/5.26.1 /home/shlomif/apps/perl/modules/lib/perl5/5.26.1 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /home/shlomif/perl5/lib/perl5/5.32.0 /home/shlomif/perl5/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /home/shlomif/perl5/lib/perl5/5.32.0 /home/shlomif/perl5/lib/perl5/5.32.0/x86_64-linux-gnu-thread-multi /usr/local/lib/site_perl .) at /usr/share/perl/5.32/Module/Load.pm line 77.
Compilation failed in require at /home/shlomif/perl5/lib/perl5/Plack/Request.pm line 17.
BEGIN failed--compilation aborted at /home/shlomif/perl5/lib/perl5/Plack/Request.pm line 17.
Compilation failed in require at /usr/lib/x86_64-linux-gnu/perl-base/parent.pm line 16.
BEGIN failed--compilation aborted at /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib/Dancer2/Core/Request.pm line 6.
Compilation failed in require at /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib/Dancer2/Core/App.pm line 28.
BEGIN failed--compilation aborted at /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib/Dancer2/Core/App.pm line 28.
Compilation failed in require at /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib/Dancer2.pm line 11.
BEGIN failed--compilation aborted at /home/shlomif/.cpanm/work/1631001608.244233/Dancer2-0.301004/blib/lib/Dancer2.pm line 11.
Compilation failed in require at -e line 1.
```

[build.log.txt](https://github.com/PerlDancer/Dancer2/files/7119994/build.log.txt)

I am on debian bookworm "testing".

**Comment by EvanCarroll** [comment] 2021-09-09 07:30
I'm just guessing, but they need to add `WWW::Form::UrlEncoded` to https://github.com/PerlDancer/Dancer2/blob/master/cpanfile

**Comment by shlomif** [comment] 2021-09-09 07:49
This fails as well:

```
[shlomif@telaviv ~]$ cpanm HTTP::Entity::Parser::UrlEncoded 
HTTP::Entity::Parser::UrlEncoded is up to date. (undef)
[shlomif@telaviv ~]$ cpanm --reinstall Dancer2                                
```

**Comment by SysPete** [comment] 2021-09-11 14:30
This looks like a broken stack, where `HTTP::Entity::Parser::UrlEncoded` was previously installed and then `WWW::Form::UrlEncoded` was removed, perhaps using `cpanm -U`, and this is in fact the only way I can reproduce the issue. Can fixed via `cpanm --reinstall HTTP::Entity::Parser::UrlEncoded`.

**Comment by SysPete** [comment] 2021-09-11 14:31
Closing, as this is a Perl toolchain issue, and not something we can fix in Dancer2.

**Closed by SysPete** 2021-09-11 14:31 UTC
