### ISSUE TITLE
Plugin::LogReport broken by plugin2

### ISSUE THREAD

**Issue by SysPete** [PerlDancer/Dancer2#1156] opened 2016-04-12 16:41 UTC
https://github.com/PerlDancer/Dancer2/issues/1078#issuecomment-204963860 says:

Thanks @xsawyerx - I will give some better details when I get a chance to look into it properly, but (from memory) it basically boils down to no longer being able to import functions (or pass options) when loading a plugin. Although one could argue that this is not what a plugin is for, it is nonetheless a regression from the old system. It is also very useful to be able to do so: imagine that you have a "normal" module that exports a bunch of functions, and you want a Dancer plugin variant (as is the case with LogReport). It's much nicer being able to load a plugin and get all the normal module functionality plus some special Dancer things, rather than to have to load both the core module plus the plugin.

Like I say, I'll pass more details when I get a chance, I just wanted to give an initial heads-up. Thanks.

**Comment by SysPete** [comment] 2016-04-13 08:46
@andybev do you have any more to add to this issue?

**Comment by racke** [comment] 2016-04-13 08:48
I understand that @abeverly wants to solve the problem with his plugin, but I don't like that this delays the next Dancer release. Also the lack of a Git repository makes it harder for us to try to
solve it on our own.

**Comment by veryrusty** [comment] 2016-04-13 11:18
The lack of a repo isn't a showstopper. Try:  https://github.com/veryrusty/MARKOV-Log-Report-1.14.git
[ Its an import of the Log::Report v1.14 release from CPAN, so there is no history. Should I move it to the PerlDancer org to make committing easier ? ]

**Comment by SysPete** [comment] 2016-04-13 11:50
@veryrusty having repo under PerlDancer makes sense.

**Comment by veryrusty** [comment] 2016-04-13 11:54
@SysPete Repo moved:  https://github.com/PerlDancer/MARKOV-Log-Report-1.14.git

**Comment by SysPete** [comment] 2016-04-13 11:57
@veryrusty could you please add Core team to that repo? I don't have commit bit atm.

**Comment by veryrusty** [comment] 2016-04-13 11:59
@SysPete Done (the migration gave read-only access to core - should have been admin .. oh well)

**Comment by xsawyerx** [comment] 2016-04-14 08:51
Going up on a flight, will investigate during!

**Comment by xsawyerx** [comment] 2016-04-14 08:52
I think whatever happens, this weekend we should already do a developer release.

**Comment by SysPete** [comment] 2016-04-14 08:56
@xsawyerx excellent news on both counts. Dev release will be especially good.

**Comment by racke** [comment] 2016-04-14 08:56
Yes, please do a developer release and have a save flight!

**Comment by abeverley** [comment] 2016-04-18 10:21
Sorry for the delay responding. I've rerun the testing on the master branch of Dancer2. The first problem is the one that I had when testing with Yanick's original branch: https://github.com/PerlDancer/Dancer2/pull/1010#issuecomment-167352901. I can fix that by using ```_exporter_validate_opts``` instead of ```import```, although it does seem a little hacky and I never got a response to my question in the moops IRC channel as to whether this should be done or not. It also means a concurrent release of a new plugin version alongside Dancer2, but I can live with that.

The second problem, which I can't work out how to fix, is that it's no longer possible to pass options to a plugin. I get ```Specific subroutines cannot be exported from plugin```. Firstly it would be nice if specific subroutines *could* be exported, as they can with the current plugin system, but secondly it means that options can't be passed either, which is also possible with the current plugin system. Any ideas please @xsawyerx?

Thanks, Andy

**Comment by xsawyerx** [comment] 2016-04-19 15:38
@abeverley Indeed importing options are not available. I don't remember us ever documenting this can be done, so we might fall under "well, it worked, so we did it".

What if you the import-time configuration in the settings and then introduce it on plugin import?

**Comment by abeverley** [comment] 2016-04-19 17:57
Thanks for the reply @sawyerx

> What if you the import-time configuration in the settings and then
> introduce it on plugin import?

Potentially, but:

- the problem is also that functions can no longer be imported, whereas they can with the current plugin system

- I'm trying to replicate the functionality of the parent module as closely is possible, which I think would potentially be quite desirable for other modules. Let's say you have module Foo::Bar and you want a Dancer2 specific version. At the moment you can create Dancer2::Plugin::FooBar and have exactly the same functionality as the original module (functions, options etc), but with Dancer2 specifics. That's what I'm doing with Log::Report - it has quite a few functions and options, which I'd like to be able to use with the plugin exactly as can be used with the main module. Sure, I could maybe export the functions as plugin keywords (although I'm not 100% sure), but then I've got to keep a whole bunch of keywords in sync with the main module, and you also lose the ability to selectively import.

So, given that the functionality is both present in the current architecture and (IMHO) desirable, I would be grateful if it could be retained.

Thanks,

Andy

**Comment by abeverley** [comment] 2016-04-19 18:12
Correction: I can import functions with the method detailed in the previous comment. The other comments still stand though. Thanks.

**Comment by veryrusty** [comment] 2016-05-18 04:39
I've pushed a half dozen commits to:
  https://github.com/PerlDancer/MARKOV-Log-Report-1.14/tree/feature/plugin2

I _think_ these resolve @abeverley concerns (or at least as far as I've grok'd them). The `t/70dancer2.t` test passes with both Dancer2 v0.166001 and the trial v0.166001_02 after these changes.

The main change is to ensure the overridden `import` method in Dancer2::Plugin::LogReport
  * imports Log::Report into the appropriate caller, passing in import args, and then
  * ensure the overridden import method is also called (with the appropriate caller).

No import args get passed to Export::Tiny this way, so you can't rename imports, etc. That may not be a big deal.

**Comment by abeverley** [comment] 2016-05-18 06:24
Brilliant, thanks @veryrusty, much appreciated. I'll take a look in a bit.

**Comment by racke** [comment] 2016-05-18 06:38
@veryrusty :+1:

**Comment by xsawyerx** [comment] 2016-05-18 07:34
@veryrusty++ :+1: :+1:

**Comment by veryrusty** [comment] 2016-05-22 10:12
@abeverley did you get a chance to look at those changes ?

**Comment by abeverley** [comment] 2016-05-22 15:03
Sorry for the delay @veryrusty . I've just tried them now, and they seem to work great. Let me just run them by @markov2 and check whether I've missed anything, but it certainly seems to fix all the problems I had. Thanks for your help.

**Comment by SysPete** [comment] 2016-05-22 20:49
@veryrusty++ :+1: So if all is working we need to look at remaining problems in #1078.

**Comment by SysPete** [comment] 2016-05-26 16:43
@abeverley we're hoping to get new D2 release out in the next few days. Please let us know what the status is.

**Comment by markov2** [comment] 2016-05-27 07:01
* Peter Mottram (notifications@github.com) [160526 16:43]:
> @abeverley we're hoping to get new D2 release out in the next few
> days. Please let us know what the status is.

I have just released Log::Report v1.16, with the patches by Russell.
-- 
greetz,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by veryrusty** [comment] 2016-05-27 07:24
Thanks heaps @markov2

**Comment by veryrusty** [comment] 2016-05-27 10:35
Resolving this issue not that Log::Report v1.16 has hit the CPAN. 

Thanks to everyone involved!!

**Closed by veryrusty** 2016-05-27 10:35 UTC

**Comment by xsawyerx** [comment] 2016-05-27 11:13
Great work, everyone!
