### ISSUE TITLE
Dancer2 loads multiple configs (files and formats)

### ISSUE THREAD

**Issue by perlpilot** [PerlDancer/Dancer2#1149] opened 2016-04-04 13:15 UTC
If there is both a config.json and a config.yaml  (or any other of the formats that Config::Any understands), Dancer2 will load and merge them all into a single configuration.  While it makes sense to have alternate config files, it makes little sense to load multiple different formats into a single configuration.

See the `_build_config_files` routine at https://github.com/PerlDancer/Dancer2/blob/master/lib/Dancer2/Core/Role/ConfigReader.pm#L106

**Comment by xsawyerx** [comment] 2016-04-04 13:45
Agreed.

**Comment by cromedome** [comment] 2016-04-04 14:04
I think it would be easy enough to stop looping through possible extensions once we hit on a file/extension combination that works. The problem is, unless we specify an order for the extensions, the file we get might not be the one we expect. And while I don't expect that `Config::Any` will change what it supports anytime soon, we need to be mindful of the fact that if we specify the order of extensions to search, one might get added later that we miss.

I can easily patch things so we stop looking at extensions once we have a match, but what about the order of them? @perlpilot? @xsawyerx? Anyone else? :grinning:

**Comment by xsawyerx** [comment] 2016-04-04 14:18
Basic order from `Config::Any` is good enough. Having a warning when we have multiple files (so a user understands why it read the YAML file but not the JSON file) would also be useful.

@cromedome also mentioned having an environment variable available to control that, a la:

    DANCER_CONFIGFILE="config.yml"

or

    DANCER_CONFIGFILE_EXT="json"

In which case I think the warning for multiple files should not be printed, because you're explicitly narrowing the field.

**Comment by veryrusty** [comment] 2016-04-05 00:07
I view this as a poorly documented feature than a bug.

I've had one use-case where I wanted a hand written and commented config augmented with configuration generated from an orchestration tool. Having `config.yaml` and `config.json` made that easy.  TIMTOWTDI applies of course, but the dual config files was a simple solution.

**Comment by xsawyerx** [comment] 2016-04-05 09:17
The alternative would be to document this as intended behavior.

Honestly, you raise a good use case and I could swing either way.

**Comment by perlpilot** [comment] 2016-04-05 13:24
Problems I see with this "feature" as currently implemented:
* Future developers will be wondering why there's both a `config.json` and a `config.yaml` causing potential confusion.
* Not everyone has the luxury of using multiple config file formats
* For people not using multiple config file formats, they will have a `config.yaml` and a `config.yml` which, to my mind looks even more hacky (Why two YAML config files instead of just one?)
* And if your project's preferred config file format is INI, you're out of luck because there's only one file extension that gets recognized as INI format.  Same for XML.
* Files are push onto an array, then the array is sorted.  When the config is merged, later config files take precedent over earlier ones.  So there's no way to have info in your `config.json` override info in your `config.yaml` because the latter always collates after the former.  (get rid of the sort and you're left with whatever order `Config::Any->extensions` comes in, which appears to be sorted, but isn't guaranteed to be, nor is it guaranteed to be in the same order from one version of Config::Any to another)

@veryrusty's use-case is very similar to the thing I wanted to accomplish--developer-specific configuration information that does not get checked into revision control.  (i.e.  something like `environments/development.yaml` (in git) + `environments/my-development.yaml` (not in git) but both get loaded and combined in a sane way with `my-` config overriding whatever is in the default config)

So, IMHO, the "right" solution is to only load one config file format per location (i.e. `config.json` xor `config.yaml`; never both) and
* provide a special name/location that devs can use for loading after the default config files (as above and in #1150), or
* provide a way for devs to specify an alternate config file to look for after the default config (e.g., maybe have an environment variable DANCER_ALT_CONFIG that specifies a path to a particular file which gets loaded after the environmental config), or
* maybe both of these things

**Comment by veryrusty** [comment] 2016-05-09 12:56
Linking this to #47 (second oldest open ticket!)

**Comment by cromedome** [comment] 2016-10-10 02:37
Resolved by e9a633d0851f42fa5822151920180a40887a8dbc. Closing. Thank you!

**Closed by cromedome** 2016-10-10 02:37 UTC
Labels: Question
